import { NextResponse } from 'next/server';
import { createClient as createSupabaseServerClient } from '@/utils/supabase/server';
import { createClient as createSupabaseAdminClient } from '@supabase/supabase-js';
import type { Database } from '@/types/supabase';

export async function POST() {
  const supabase = await createSupabaseServerClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ ok: false, error: 'Not signed in' }, { status: 401 });
  }

  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!supabaseUrl || !serviceRoleKey) {
    return NextResponse.json(
      {
        ok: false,
        error:
          'Missing SUPABASE_SERVICE_ROLE_KEY. Add it to .env.local so the server can ensure your profiles row exists.',
      },
      { status: 500 },
    );
  }

  const admin = createSupabaseAdminClient<Database>(supabaseUrl, serviceRoleKey, {
    auth: { persistSession: false },
  });

  const email = user.email ?? `${user.id}@drifd.local`;
  const baseUsername =
    (typeof user.user_metadata?.username === 'string' && user.user_metadata.username.trim()) ||
    (user.email ? user.email.split('@')[0] : 'DrifdUser');
  const username = `${baseUsername}`.slice(0, 20) + '-' + user.id.slice(0, 4);
  const imageurl =
    (typeof user.user_metadata?.imageUrl === 'string' && user.user_metadata.imageUrl.trim()) ?
      user.user_metadata.imageUrl
    : (typeof user.user_metadata?.avatar_url === 'string' && user.user_metadata.avatar_url.trim()) ?
        user.user_metadata.avatar_url
      : (typeof user.user_metadata?.picture === 'string' && user.user_metadata.picture.trim()) ?
          user.user_metadata.picture
        : null;

  const { data: existingProfile, error: existingProfileError } = await admin
    .schema('public')
    .from('profiles')
    .select('id, username, imageurl')
    .eq('id', user.id)
    .maybeSingle();

  if (existingProfileError) {
    const message = existingProfileError.message || 'Unknown error';
    return NextResponse.json({ ok: false, error: message }, { status: 500 });
  }

  let error: { message?: string } | null = null;

  if (!existingProfile) {
    const insertResult = await admin
      .schema('public')
      .from('profiles')
      .insert({
        id: user.id,
        email,
        username,
        imageurl,
      });

    error = (insertResult.error as { message?: string } | null) ?? null;
  } else {
    // Preserve existing customized profile fields. Only patch obviously broken data
    // produced by previous ensure upsert behavior.
    const patch: { email?: string; username?: string; imageurl?: string | null } = {};
    let shouldPatch = false;

    patch.email = email;
    shouldPatch = true;

    const generatedBuggyUsername = username;
    const existingUsername = (existingProfile as { username?: string | null }).username;
    const existingImageUrl = (existingProfile as { imageurl?: string | null }).imageurl;

    // Repair only when username matches our old autogenerated pattern exactly.
    if (existingUsername && existingUsername === generatedBuggyUsername && baseUsername) {
      patch.username = baseUsername;
      shouldPatch = true;
    }

    // Fill avatar only when currently empty and auth metadata has a usable avatar.
    if (!existingImageUrl && imageurl) {
      patch.imageurl = imageurl;
      shouldPatch = true;
    }

    if (shouldPatch) {
      const updateResult = await admin
        .schema('public')
        .from('profiles')
        .update(patch)
        .eq('id', user.id);

      error = (updateResult.error as { message?: string } | null) ?? null;
    }
  }

  if (error) {
    const message = error.message || 'Unknown error';
    const looksLikeMissingProfiles =
      message.includes("Could not find the table 'public.profiles'") ||
      message.toLowerCase().includes('schema cache') && message.toLowerCase().includes('profiles');

    if (looksLikeMissingProfiles) {
      return NextResponse.json(
        {
          ok: false,
          error:
            "Supabase DB şeması kurulmamış görünüyor: public.profiles bulunamadı. Supabase Dashboard > SQL Editor'da repodaki supabase_schema.sql dosyasını çalıştır. Sonra Settings > API > Schemas kısmında 'public' seçili olduğundan emin ol. (Gerekirse SQL Editor'da: NOTIFY pgrst, 'reload schema';)",
        },
        { status: 500 },
      );
    }

    return NextResponse.json({ ok: false, error: message }, { status: 500 });
  }

  return NextResponse.json({ ok: true });
}
